package com.szxb.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.szxb.entity.HomeInfoEntity;

import com.szxb.db.dao.HomeInfoEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeInfoEntityDaoConfig;

    private final HomeInfoEntityDao homeInfoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeInfoEntityDaoConfig = daoConfigMap.get(HomeInfoEntityDao.class).clone();
        homeInfoEntityDaoConfig.initIdentityScope(type);

        homeInfoEntityDao = new HomeInfoEntityDao(homeInfoEntityDaoConfig, this);

        registerDao(HomeInfoEntity.class, homeInfoEntityDao);
    }
    
    public void clear() {
        homeInfoEntityDaoConfig.clearIdentityScope();
    }

    public HomeInfoEntityDao getHomeInfoEntityDao() {
        return homeInfoEntityDao;
    }

}
